language: node_js
node_js:
  - 12
cache: yarn
jobs:
  include:
  - name: lint
    script:
    - yarn lint:strict
  - name: test
    script:
    - cp conf/config.travis.yml conf/config.yml
    - yarn build
    - yarn test
  allow_failures:
  - name: lint
notifications:
  webhooks:
    urls:
      - secure: "Gzr64dnvwwOzElM7JYeP24l7wmZQ3Zffh6vuWUsf9YPBNuGWHoUxOI2vjU7Y9dm1mS+D/8keOLZIlqkhVeE8DP4scRiTedmN/dnvYk9rUrGdY8rui/eCHpUx2CfVjhBq4i+hg5lMjQyg27fxOfdiG+E34LsMl9A0lKjobGB0NeT2bBwNTEYyuA/+wtYw/9a0SVU911+VHR9b0WdPWo/okBVUv7+qe7nPGwWXM1ekdyvp1HBL4IzTNemcdkdDu4u75v7Twsizk2TP03NwrPLG9rznU+FYiVOPXKoIVbmNAvDiBSIZpav4dHEGmkoUely++xy88XBCnTwa6+xoUcQGF1c5uZoOePCO9RcUv+Bgez0cT2eoetSzJ89aKJ9ZdAGIwJT8gW7Ryk1db6o2jDH7D4bd9urac9AIF3O2HzS5xyRPFXT9Zw+zlsr4Zy2rfsAYJAdbEU+y2k+/7EmAoy1Y2N9GGysA1DENbRDJCtDLgr/YsGNaUz0KIuvjBNm+LiELg7N8britFZaVTvSqUGlo7nmi2wg4Pjk3Jm9KmoZvfdjshPhxk62RLWt6E6K7/vMBrm+JrMAwuMFcYIELcS6NsbkjJUJXsXaVbpBABVJTZJQcC6zMuXGPyQVjPgyiinfLrzqyaGSFqI2gjMDmb8pSVHxsqIntht0E6YfyXvup9Ag="
    on_success: change
    on_failure: always
    on_start: change
    on_cancel: always
    on_error: always
